/-
  The ϑ-notation system for the Bachmann–Howard ordinal: terms, length, coefficients,
  the order, and the normal form.

  Source: A. Freund, *Impredicativity and trees with gap condition: a second course on
  ordinal analysis*, arXiv:2204.09321, Definition 3.1 (the system is due to Rathjen and
  Weiermann).  The terms are generated by

  * `Ω`,
  * `ϑ α` for every term `α`,
  * `⟨α₀, …, α_{n-1}⟩` for every finite list of terms (`n = 0` is allowed and gives `0`);
    this term is meant to denote the Cantor sum `ω^α₀ + ⋯ + ω^α_{n-1}`.

  Following Freund, the order `≺` is defined on all raw terms (the set `ϑ⁰(ε_{Ω+1})` of
  Freund, where the ordering condition on sums is dropped), by recursion on `l α + l β` for
  the length function `l`.  The normal form (the set `ϑ(ε_{Ω+1})`) is then cut out by the
  conditions of Definition 3.1 (iii): the entries of a sum are non-increasing, and a
  one-element sum `⟨α₀⟩` does not have `α₀` of the form `Ω` or `ϑ β`.

  The finite set `E(α)` of Definition 3.1 is represented by a list: `E(Ω) = ∅`,
  `E(ϑ α) = {ϑ α}`, and `E(⟨α₀, …, α_{n-1}⟩)` is the union of the `E(α_i)`.

  This file contains the definitions, the recursion equations of the order clause by clause,
  and elementary facts about `l` and `E`.  The order-theoretic properties (irreflexivity,
  transitivity, totality) are proved in the companion module on the order.
-/
import Mathlib.Data.List.Basic

set_option autoImplicit false

namespace OrdinalAnalysis

/-- Raw terms of the ϑ-notation system (Freund, arXiv:2204.09321, Definition 3.1):
`Omega` is `Ω`, `theta α` is `ϑ α`, and `sum [α₀, …, α_{n-1}]` is `⟨α₀, …, α_{n-1}⟩`. -/
inductive ThetaTerm : Type
  | Omega : ThetaTerm
  | theta : ThetaTerm → ThetaTerm
  | sum : List ThetaTerm → ThetaTerm
  deriving Repr

namespace ThetaTerm

/-! ### Decidable equality -/

mutual
/-- Decidable equality of terms, by structural recursion. -/
def decEq : (a b : ThetaTerm) → Decidable (a = b)
  | Omega, Omega => isTrue rfl
  | Omega, theta _ => isFalse (fun h => ThetaTerm.noConfusion h)
  | Omega, sum _ => isFalse (fun h => ThetaTerm.noConfusion h)
  | theta _, Omega => isFalse (fun h => ThetaTerm.noConfusion h)
  | theta a, theta b =>
    match decEq a b with
    | isTrue h => isTrue (h ▸ rfl)
    | isFalse h => isFalse (fun e => h (theta.inj e))
  | theta _, sum _ => isFalse (fun h => ThetaTerm.noConfusion h)
  | sum _, Omega => isFalse (fun h => ThetaTerm.noConfusion h)
  | sum _, theta _ => isFalse (fun h => ThetaTerm.noConfusion h)
  | sum xs, sum ys =>
    match decEqList xs ys with
    | isTrue h => isTrue (h ▸ rfl)
    | isFalse h => isFalse (fun e => h (sum.inj e))
/-- Decidable equality of lists of terms, by structural recursion. -/
def decEqList : (xs ys : List ThetaTerm) → Decidable (xs = ys)
  | [], [] => isTrue rfl
  | [], _ :: _ => isFalse (by intro h; cases h)
  | _ :: _, [] => isFalse (by intro h; cases h)
  | x :: xs, y :: ys =>
    match decEq x y, decEqList xs ys with
    | isTrue h1, isTrue h2 => isTrue (h1 ▸ h2 ▸ rfl)
    | isFalse h1, _ => isFalse (fun e => h1 (List.cons.inj e).1)
    | _, isFalse h2 => isFalse (fun e => h2 (List.cons.inj e).2)
end

instance : DecidableEq ThetaTerm := decEq

/-- The term `0 = ⟨⟩`. -/
def zero : ThetaTerm := sum []

/-- `Ω` and the terms `ϑ α` are the principal terms (they denote ε-numbers). -/
def IsPrin : ThetaTerm → Prop
  | Omega => True
  | theta _ => True
  | sum _ => False

instance : DecidablePred IsPrin := fun a =>
  match a with
  | Omega => isTrue trivial
  | theta _ => isTrue trivial
  | sum _ => isFalse id

@[simp] theorem isPrin_Omega : IsPrin Omega := trivial
@[simp] theorem isPrin_theta (a : ThetaTerm) : IsPrin (theta a) := trivial
@[simp] theorem not_isPrin_sum (xs : List ThetaTerm) : ¬ IsPrin (sum xs) := id

/-! ### Length -/

mutual
/-- The length function of Freund (after Definition 3.1): `l(Ω) = 0`, `l(ϑ α) = l(α) + 1`,
`l(⟨α₀, …, α_{n-1}⟩) = n + Σ l(α_i)`. -/
def l : ThetaTerm → ℕ
  | Omega => 0
  | theta a => l a + 1
  | sum xs => lList xs
/-- `lList [α₀, …, α_{n-1}] = n + Σ l(α_i)`. -/
def lList : List ThetaTerm → ℕ
  | [] => 0
  | x :: xs => l x + 1 + lList xs
end

@[simp] theorem l_Omega : l Omega = 0 := by simp [l]
@[simp] theorem l_theta (a : ThetaTerm) : l (theta a) = l a + 1 := by simp [l]
@[simp] theorem l_nil : l (sum []) = 0 := by simp [l, lList]
@[simp] theorem l_cons (x : ThetaTerm) (xs : List ThetaTerm) :
    l (sum (x :: xs)) = l x + 1 + l (sum xs) := by simp [l, lList]

theorem l_lt_of_mem {x : ThetaTerm} {xs : List ThetaTerm} (h : x ∈ xs) : l x < l (sum xs) := by
  induction xs with
  | nil => cases h
  | cons y ys ih =>
    rcases List.mem_cons.mp h with rfl | h
    · simp; omega
    · have := ih h; simp; omega

/-! ### The coefficient sets `E` -/

mutual
/-- The set `E(α)` of Freund, Definition 3.1, as a list: `E(Ω) = ∅`, `E(ϑ α) = {ϑ α}`,
`E(⟨α₀, …, α_{n-1}⟩) = ⋃ E(α_i)`. -/
def E : ThetaTerm → List ThetaTerm
  | Omega => []
  | theta a => [theta a]
  | sum xs => EList xs
/-- The union of the `E(α_i)` over a list. -/
def EList : List ThetaTerm → List ThetaTerm
  | [] => []
  | x :: xs => E x ++ EList xs
end

@[simp] theorem E_Omega : E Omega = [] := by simp [E]
@[simp] theorem E_theta (a : ThetaTerm) : E (theta a) = [theta a] := by simp [E]
@[simp] theorem E_nil : E (sum []) = [] := by simp [E, EList]
@[simp] theorem E_cons (x : ThetaTerm) (xs : List ThetaTerm) :
    E (sum (x :: xs)) = E x ++ E (sum xs) := by simp [E, EList]

theorem mem_E_sum {g : ThetaTerm} {xs : List ThetaTerm} :
    g ∈ E (sum xs) ↔ ∃ x ∈ xs, g ∈ E x := by
  induction xs with
  | nil => simp
  | cons y ys ih => simp [ih]

/-- Freund, after Definition 3.1: `α' ∈ E(α)` implies `l(α') ≤ l(α)`. -/
theorem l_le_of_mem_E : ∀ {a g : ThetaTerm}, g ∈ E a → l g ≤ l a
  | Omega, g, h => by simp at h
  | theta a, g, h => by simp at h; simp [h]
  | sum xs, g, h => by
    obtain ⟨x, hx, hg⟩ := mem_E_sum.mp h
    have := l_lt_of_mem hx
    have := l_le_of_mem_E hg
    omega
termination_by a => l a
decreasing_by exact l_lt_of_mem hx

/-- Every element of `E(α)` is a term `ϑ δ`. -/
theorem exists_eq_theta_of_mem_E : ∀ {a g : ThetaTerm}, g ∈ E a → ∃ d, g = theta d
  | Omega, g, h => by simp at h
  | theta a, g, h => by simp at h; exact ⟨a, h⟩
  | sum xs, g, h => by
    obtain ⟨x, hx, hg⟩ := mem_E_sum.mp h
    exact exists_eq_theta_of_mem_E hg
termination_by a => l a
decreasing_by exact l_lt_of_mem hx

theorem mem_E_of_mem {x g : ThetaTerm} {xs : List ThetaTerm} (hx : x ∈ xs) (hg : g ∈ E x) :
    g ∈ E (sum xs) :=
  mem_E_sum.mpr ⟨x, hx, hg⟩

/-! ### The order

The relation `α ≺ β` of Freund, Definition 3.1, clauses (i')–(iii'), computed by
recursion on `l α + l β`.  In the clauses, `α ≼ β` abbreviates `α ≺ β ∨ α = β`; the
lexicographic clause for two sums is unfolded one entry at a time (the first entries are
compared, and on equality the tails are compared), which is the recursive reading of
"for some `j ≤ min(m, n)` we have `α_i = β_i` for all `i < j` and either `j = m < n` or
`j < min(m, n)` and `α_j ≺ β_j`". -/

/-- The order of Freund, Definition 3.1, as a boolean function. -/
def ltb : ThetaTerm → ThetaTerm → Bool
  -- (i') `Ω ≺ β` iff `β = ⟨β₀, …⟩` with `Ω ≼ β₀`
  | Omega, Omega => false
  | Omega, theta _ => false
  | Omega, sum [] => false
  | Omega, sum (b :: _) => ltb Omega b || decide (Omega = b)
  -- (ii') `ϑ α' ≺ β`
  | theta _, Omega => true
  | theta a, theta b =>
      (ltb a b && (E a).attach.all (fun g => ltb g.1 (theta b))) ||
        (E b).attach.any (fun g => ltb (theta a) g.1 || decide (theta a = g.1))
  | theta _, sum [] => false
  | theta a, sum (b :: _) => ltb (theta a) b || decide (theta a = b)
  -- (iii') `⟨α₀, …, α_{m-1}⟩ ≺ β`
  | sum [], Omega => true
  | sum (a :: _), Omega => ltb a Omega
  | sum [], theta _ => true
  | sum (a :: _), theta b => ltb a (theta b)
  | sum [], sum [] => false
  | sum [], sum (_ :: _) => true
  | sum (_ :: _), sum [] => false
  | sum (a :: as), sum (b :: bs) => ltb a b || (decide (a = b) && ltb (sum as) (sum bs))
termination_by a b => l a + l b
decreasing_by
  all_goals simp only [l_Omega, l_theta, l_cons]
  all_goals first
    | omega
    | (have := l_le_of_mem_E g.2; omega)

instance : LT ThetaTerm := ⟨fun a b => ltb a b = true⟩

/-- `α ≼ β` is `α ≺ β ∨ α = β`, as in Freund, Definition 3.1. -/
instance : LE ThetaTerm := ⟨fun a b => a < b ∨ a = b⟩

theorem lt_def {a b : ThetaTerm} : a < b ↔ ltb a b = true := Iff.rfl

theorem le_def {a b : ThetaTerm} : a ≤ b ↔ a < b ∨ a = b := Iff.rfl

instance decidableLT : DecidableRel (α := ThetaTerm) (· < ·) :=
  fun a b => inferInstanceAs (Decidable (ltb a b = true))

instance decidableLE : DecidableRel (α := ThetaTerm) (· ≤ ·) :=
  fun a b => inferInstanceAs (Decidable (a < b ∨ a = b))

theorem le_refl' (a : ThetaTerm) : a ≤ a := Or.inr rfl

theorem le_of_lt' {a b : ThetaTerm} (h : a < b) : a ≤ b := Or.inl h

/-! ### The clauses of the order, one constructor pair at a time -/

section Clauses

variable (a b : ThetaTerm) (as bs : List ThetaTerm)

private theorem le_iff_bool {x y : ThetaTerm} :
    (ltb x y || decide (x = y)) = true ↔ x ≤ y := by
  simp [le_def, lt_def]

/-- Clause (i'). -/
theorem not_Omega_lt_Omega : ¬ Omega < Omega := by
  rw [lt_def, ltb.eq_def]; simp

/-- Clause (i'). -/
theorem not_Omega_lt_theta : ¬ Omega < theta b := by
  rw [lt_def, ltb.eq_def]; simp

/-- Clause (i'). -/
theorem not_Omega_lt_nil : ¬ Omega < sum [] := by
  rw [lt_def, ltb.eq_def]; simp

/-- Clause (i'): `Ω ≺ ⟨β₀, …⟩ ↔ Ω ≼ β₀`. -/
theorem Omega_lt_cons_iff : Omega < sum (b :: bs) ↔ Omega ≤ b := by
  rw [lt_def, ltb.eq_def]; exact le_iff_bool

/-- Clause (ii'): `ϑ α ≺ Ω`. -/
theorem theta_lt_Omega : theta a < Omega := by
  rw [lt_def, ltb.eq_def]

/-- Clause (ii'), the ϑ-ϑ case: `ϑ α ≺ ϑ β` iff `α ≺ β` and `E(α) ≺* ϑ β`, or
`ϑ α ≼ γ` for some `γ ∈ E(β)` (Freund, Exercise 3.2(a)). -/
theorem theta_lt_theta_iff :
    theta a < theta b ↔
      (a < b ∧ ∀ g ∈ E a, g < theta b) ∨ ∃ g ∈ E b, theta a ≤ g := by
  rw [lt_def, ltb.eq_def]
  simp only [Bool.or_eq_true, Bool.and_eq_true, List.all_eq_true, List.any_eq_true,
    List.mem_attach, true_imp_iff, true_and, Subtype.forall, Subtype.exists, decide_eq_true_eq]
  simp only [← lt_def, ← le_def]
  constructor
  · rintro (⟨h1, h2⟩ | ⟨g, hg, h⟩)
    · exact Or.inl ⟨h1, fun g hg => h2 g hg⟩
    · exact Or.inr ⟨g, hg, h⟩
  · rintro (⟨h1, h2⟩ | ⟨g, hg, h⟩)
    · exact Or.inl ⟨h1, fun g hg => h2 g hg⟩
    · exact Or.inr ⟨g, hg, h⟩

/-- Clause (ii'). -/
theorem not_theta_lt_nil : ¬ theta a < sum [] := by
  rw [lt_def, ltb.eq_def]; simp

/-- Clause (ii'): `ϑ α ≺ ⟨β₀, …⟩ ↔ ϑ α ≼ β₀`. -/
theorem theta_lt_cons_iff : theta a < sum (b :: bs) ↔ theta a ≤ b := by
  rw [lt_def, ltb.eq_def]; exact le_iff_bool

/-- Clause (iii'): `⟨⟩ ≺ Ω`. -/
theorem nil_lt_Omega : sum [] < Omega := by
  rw [lt_def, ltb.eq_def]

/-- Clause (iii'): `⟨α₀, …⟩ ≺ Ω ↔ α₀ ≺ Ω`. -/
theorem cons_lt_Omega_iff : sum (a :: as) < Omega ↔ a < Omega := by
  rw [lt_def, ltb.eq_def]; rfl

/-- Clause (iii'): `⟨⟩ ≺ ϑ β`. -/
theorem nil_lt_theta : sum [] < theta b := by
  rw [lt_def, ltb.eq_def]

/-- Clause (iii'): `⟨α₀, …⟩ ≺ ϑ β ↔ α₀ ≺ ϑ β`. -/
theorem cons_lt_theta_iff : sum (a :: as) < theta b ↔ a < theta b := by
  rw [lt_def, ltb.eq_def]; rfl

/-- Clause (iii'). -/
theorem not_nil_lt_nil : ¬ sum [] < sum [] := by
  rw [lt_def, ltb.eq_def]; simp

/-- Clause (iii'): a proper prefix is smaller. -/
theorem nil_lt_cons : sum [] < sum (b :: bs) := by
  rw [lt_def, ltb.eq_def]

/-- Clause (iii'). -/
theorem not_cons_lt_nil : ¬ sum (a :: as) < sum [] := by
  rw [lt_def, ltb.eq_def]; simp

/-- Clause (iii'), lexicographic comparison, one entry at a time. -/
theorem cons_lt_cons_iff :
    sum (a :: as) < sum (b :: bs) ↔ a < b ∨ (a = b ∧ sum as < sum bs) := by
  rw [lt_def, ltb.eq_def]
  simp [lt_def]

end Clauses

/-- The principal terms against sums: `P ≺ ⟨⟩` never holds. -/
theorem not_prin_lt_nil {p : ThetaTerm} (hp : IsPrin p) : ¬ p < sum [] := by
  cases p with
  | Omega => exact not_Omega_lt_nil
  | theta a => exact not_theta_lt_nil a
  | sum _ => exact absurd hp id

/-- The principal terms against sums: `P ≺ ⟨β₀, …⟩ ↔ P ≼ β₀`. -/
theorem prin_lt_cons_iff {p b : ThetaTerm} {bs : List ThetaTerm} (hp : IsPrin p) :
    p < sum (b :: bs) ↔ p ≤ b := by
  cases p with
  | Omega => exact Omega_lt_cons_iff b bs
  | theta a => exact theta_lt_cons_iff a b bs
  | sum _ => exact absurd hp id

/-- Sums against principal terms: `⟨⟩ ≺ P`. -/
theorem nil_lt_prin {p : ThetaTerm} (hp : IsPrin p) : sum [] < p := by
  cases p with
  | Omega => exact nil_lt_Omega
  | theta b => exact nil_lt_theta b
  | sum _ => exact absurd hp id

/-- Sums against principal terms: `⟨α₀, …⟩ ≺ P ↔ α₀ ≺ P`. -/
theorem cons_lt_prin_iff {p a : ThetaTerm} {as : List ThetaTerm} (hp : IsPrin p) :
    sum (a :: as) < p ↔ a < p := by
  cases p with
  | Omega => exact cons_lt_Omega_iff a as
  | theta b => exact cons_lt_theta_iff a b as
  | sum _ => exact absurd hp id

/-! ### The comparison function -/

/-- Three-way comparison: `.eq` on equal terms, `.lt` when `a ≺ b`, `.gt` otherwise.  That
`.gt` means `b ≺ a` is the totality of the order, proved in the companion module. -/
def cmp (a b : ThetaTerm) : Ordering :=
  if a = b then .eq else if a < b then .lt else .gt

@[simp] theorem cmp_refl (a : ThetaTerm) : cmp a a = .eq := by simp [cmp]

theorem cmp_eq_eq_iff {a b : ThetaTerm} : cmp a b = .eq ↔ a = b := by
  unfold cmp; split_ifs <;> simp_all

/-! ### Normal form

Freund, Definition 3.1 (iii): in `⟨α₀, …, α_{n-1}⟩` we have `α_{n-1} ≼ ⋯ ≼ α₀`, and if
`n = 1` then `α₀` is not of the form `Ω` or `ϑ β`; the conditions apply hereditarily. -/

/-- The entries of a list are non-increasing: `α_{i+1} ≼ α_i` for consecutive entries. -/
def Desc : List ThetaTerm → Prop
  | [] => True
  | [_] => True
  | x :: y :: ys => y ≤ x ∧ Desc (y :: ys)

instance decidableDesc : DecidablePred Desc
  | [] => isTrue trivial
  | [_] => isTrue trivial
  | x :: y :: ys =>
    haveI := decidableDesc (y :: ys)
    inferInstanceAs (Decidable (y ≤ x ∧ Desc (y :: ys)))

@[simp] theorem desc_nil : Desc [] := trivial
@[simp] theorem desc_singleton (x : ThetaTerm) : Desc [x] := trivial
@[simp] theorem desc_cons_cons (x y : ThetaTerm) (ys : List ThetaTerm) :
    Desc (x :: y :: ys) ↔ y ≤ x ∧ Desc (y :: ys) := Iff.rfl

theorem Desc.tail {x : ThetaTerm} {xs : List ThetaTerm} (h : Desc (x :: xs)) : Desc xs := by
  cases xs with
  | nil => trivial
  | cons y ys => exact h.2

/-- The one-entry condition of Definition 3.1 (iii): a sum `⟨α₀⟩` must not have `α₀`
principal. -/
def SingleOK : List ThetaTerm → Prop
  | [x] => ¬ IsPrin x
  | _ => True

instance decidableSingleOK : DecidablePred SingleOK
  | [] => isTrue trivial
  | [x] => inferInstanceAs (Decidable (¬ IsPrin x))
  | _ :: _ :: _ => isTrue trivial

mutual
/-- The normal form of Freund, Definition 3.1: the terms of `ϑ(ε_{Ω+1})`. -/
def NF : ThetaTerm → Prop
  | Omega => True
  | theta a => NF a
  | sum xs => NFList xs ∧ Desc xs ∧ SingleOK xs
/-- Every entry of the list is in normal form. -/
def NFList : List ThetaTerm → Prop
  | [] => True
  | x :: xs => NF x ∧ NFList xs
end

mutual
/-- A decision procedure for `NF`. -/
def decNF : (a : ThetaTerm) → Decidable (NF a)
  | Omega => isTrue (by simp [NF])
  | theta a =>
    match decNF a with
    | isTrue h => isTrue (by simpa [NF] using h)
    | isFalse h => isFalse (by simpa [NF] using h)
  | sum xs =>
    match decNFList xs with
    | isTrue h =>
      if hd : Desc xs ∧ SingleOK xs then isTrue (by simp only [NF]; exact ⟨h, hd⟩)
      else isFalse (by simp only [NF]; exact fun h' => hd h'.2)
    | isFalse h => isFalse (by simp only [NF]; exact fun h' => h h'.1)
/-- A decision procedure for `NFList`. -/
def decNFList : (xs : List ThetaTerm) → Decidable (NFList xs)
  | [] => isTrue (by simp [NFList])
  | x :: xs =>
    match decNF x, decNFList xs with
    | isTrue h1, isTrue h2 => isTrue (by simp only [NFList]; exact ⟨h1, h2⟩)
    | isFalse h1, _ => isFalse (by simp only [NFList]; exact fun h => h1 h.1)
    | _, isFalse h2 => isFalse (by simp only [NFList]; exact fun h => h2 h.2)
end

instance : DecidablePred NF := decNF

@[simp] theorem nf_Omega : NF Omega := by simp [NF]

@[simp] theorem nf_theta_iff (a : ThetaTerm) : NF (theta a) ↔ NF a := by simp [NF]

theorem nfList_iff {xs : List ThetaTerm} : NFList xs ↔ ∀ x ∈ xs, NF x := by
  induction xs with
  | nil => simp [NFList]
  | cons y ys ih => simp [NFList, ih]

theorem nf_sum_iff (xs : List ThetaTerm) :
    NF (sum xs) ↔ (∀ x ∈ xs, NF x) ∧ Desc xs ∧ SingleOK xs := by
  simp only [NF, nfList_iff]

theorem NF.of_mem {x : ThetaTerm} {xs : List ThetaTerm} (h : NF (sum xs)) (hx : x ∈ xs) :
    NF x :=
  ((nf_sum_iff xs).mp h).1 x hx

theorem NF.theta_arg {a : ThetaTerm} (h : NF (theta a)) : NF a := (nf_theta_iff a).mp h

theorem NF.desc {xs : List ThetaTerm} (h : NF (sum xs)) : Desc xs := ((nf_sum_iff xs).mp h).2.1

theorem nf_zero : NF zero := by simp [zero, nf_sum_iff, SingleOK]

/-- The elements of `E(α)` of a normal term are normal. -/
theorem NF.of_mem_E : ∀ {a g : ThetaTerm}, NF a → g ∈ E a → NF g
  | Omega, g, _, h => by simp at h
  | theta a, g, ha, h => by simp at h; exact h ▸ ha
  | sum xs, g, ha, h => by
    obtain ⟨x, hx, hg⟩ := mem_E_sum.mp h
    exact NF.of_mem_E (ha.of_mem hx) hg
termination_by a => l a
decreasing_by exact l_lt_of_mem hx

end ThetaTerm

/-- The ϑ-notation system `ϑ(ε_{Ω+1})` of Freund, Definition 3.1: terms in normal form. -/
def ThetaNote : Type := {t : ThetaTerm // ThetaTerm.NF t}

instance : DecidableEq ThetaNote :=
  inferInstanceAs (DecidableEq {t : ThetaTerm // ThetaTerm.NF t})

end OrdinalAnalysis
