/- Source: OrdinalAnalysis\IDn\PredCutCases\CaseNstage.lean (level `k : Fin n` generalised to `k : ℕ`, ID_n -> ID_omega). -/

import OrdinalAnalysis.IDw.PredCutAux

set_option autoImplicit false

namespace OrdinalAnalysis
namespace IDw

open LO LO.FirstOrder
-- case_skeleton: generated header ends here

/-- Case `nstage` of `predCut_aux` (generated by case_skeleton.py; statement only, dispatch=induction). -/
theorem predCut_aux_case_nstage
    {A : Semisentence LForm 2}
    {lv : ℕ}
    {μ r : ThetaVNoteD}
    (hμ : ∀ c : ThetaVNoteD, μ ≤ c → c < ThetaVNoteD.Omega lv →
      ∀ j : ℕ, c ≠ ThetaVNoteD.Omega j)
    (hr : r < ThetaVNoteD.Omega lv)
    (ihr : ∀ c : ThetaVNoteD, c < r → PredCutClaim A lv μ c)
    {H : Set ThetaVNoteD → Set ThetaVNoteD}
    {α : ThetaVNoteD}
    {Γ : Sequent (LIinfW)}
    {k : ℕ}
    {a : StageAt k}
    {t : SyntacticTerm (LIinfW)}
    (f : StageAt k → ThetaVNoteD)
    (p1 : α ∈ H ∅)
    (p2 : paramsVal Γ ⊆ H ∅)
    (p3 : nstageAt (⟨k, a⟩ : Stage) t ∈ Γ)
    (p4 : (∀ g : StageAt k, g.1 < a.1 → f g < α))
    (p5 : (∀ g : StageAt k, g.1 < a.1 →
        IDwDerivable A r (ThetaVNoteD.adjoin H {g.1}) (f g) (∼(unfoldW A k g t) :: Γ)))
    (ih5 : ∀ g : StageAt k, g.1 < a.1 → ThetaVNoteD.NiceS (ThetaVNoteD.adjoin H {g.1}) → ThetaVNoteD.PhiClosed lv (ThetaVNoteD.adjoin H {g.1}) → r ∈ (ThetaVNoteD.adjoin H {g.1}) ∅ → (f g) < ThetaVNoteD.Omega lv →
      IDwDerivable A μ (ThetaVNoteD.adjoin H {g.1}) (ThetaVNoteD.phiN lv r (f g)) (∼(unfoldW A k g t) :: Γ))
    : ThetaVNoteD.NiceS H → ThetaVNoteD.PhiClosed lv H → r ∈ H ∅ → α < ThetaVNoteD.Omega lv →
      IDwDerivable A μ H (ThetaVNoteD.phiN lv r α) Γ := by
  intro hH hP hrH hαΩ
  have hφ : ThetaVNoteD.phiN lv r α ∈ H ∅ := hP ∅ r α hr hαΩ hrH p1
  refine .nstage (fun g => ThetaVNoteD.phiN lv r (f g)) hφ p2 p3 ?_ ?_
  · intro g hg
    have hfgΩ : f g < ThetaVNoteD.Omega lv := lt_trans (p4 g hg) hαΩ
    exact ThetaVNoteD.phiN_lt_phiN_right hr hfgΩ hαΩ (p4 g hg)
  · intro g hg
    have hfgΩ : f g < ThetaVNoteD.Omega lv := lt_trans (p4 g hg) hαΩ
    have hrH' : r ∈ (ThetaVNoteD.adjoin H ({g.1} : Set ThetaVNoteD)) ∅ := by
      rw [ThetaVNoteD.adjoin_apply]
      exact hH.1.mono (Set.empty_subset _) hrH
    exact ih5 g hg (hH.adjoin _) (hP.adjoin _) hrH' hfgΩ
