/- Source: OrdinalAnalysis\IDn\PredCutCases\CaseAnd.lean (level `k : Fin n` generalised to `k : ℕ`, ID_n -> ID_omega). -/

import OrdinalAnalysis.IDw.PredCutAux

set_option autoImplicit false

namespace OrdinalAnalysis
namespace IDw

open LO LO.FirstOrder
-- case_skeleton: generated header ends here

/-- Case `and` of `predCut_aux` (generated by case_skeleton.py; statement only, dispatch=induction). -/
theorem predCut_aux_case_and
    {A : Semisentence LForm 2}
    {lv : ℕ}
    {μ r : ThetaVNoteD}
    (hμ : ∀ c : ThetaVNoteD, μ ≤ c → c < ThetaVNoteD.Omega lv →
      ∀ j : ℕ, c ≠ ThetaVNoteD.Omega j)
    (hr : r < ThetaVNoteD.Omega lv)
    (ihr : ∀ c : ThetaVNoteD, c < r → PredCutClaim A lv μ c)
    {H : Set ThetaVNoteD → Set ThetaVNoteD}
    {α : ThetaVNoteD}
    {Γ : Sequent (LIinfW)}
    {φ ψ : Proposition (LIinfW)}
    {α₀ α₁ : ThetaVNoteD}
    (p1 : α ∈ H ∅)
    (p2 : paramsVal Γ ⊆ H ∅)
    (p3 : φ ⋏ ψ ∈ Γ)
    (p4 : α₀ < α)
    (p5 : α₁ < α)
    (p6 : IDwDerivable A r H α₀ (φ :: Γ))
    (p7 : IDwDerivable A r H α₁ (ψ :: Γ))
    (ih6 : ThetaVNoteD.NiceS H → ThetaVNoteD.PhiClosed lv H → r ∈ H ∅ → α₀ < ThetaVNoteD.Omega lv →
      IDwDerivable A μ H (ThetaVNoteD.phiN lv r α₀) (φ :: Γ))
    (ih7 : ThetaVNoteD.NiceS H → ThetaVNoteD.PhiClosed lv H → r ∈ H ∅ → α₁ < ThetaVNoteD.Omega lv →
      IDwDerivable A μ H (ThetaVNoteD.phiN lv r α₁) (ψ :: Γ))
    : ThetaVNoteD.NiceS H → ThetaVNoteD.PhiClosed lv H → r ∈ H ∅ → α < ThetaVNoteD.Omega lv →
      IDwDerivable A μ H (ThetaVNoteD.phiN lv r α) Γ := by
  intro hH hP hrH hαΩ
  have hα₀Ω : α₀ < ThetaVNoteD.Omega lv := lt_trans p4 hαΩ
  have hα₁Ω : α₁ < ThetaVNoteD.Omega lv := lt_trans p5 hαΩ
  exact .and (hP ∅ r α hr hαΩ hrH p1) p2 p3
    (ThetaVNoteD.phiN_lt_phiN_right hr hα₀Ω hαΩ p4)
    (ThetaVNoteD.phiN_lt_phiN_right hr hα₁Ω hαΩ p5)
    (ih6 hH hP hrH hα₀Ω) (ih7 hH hP hrH hα₁Ω)
