/- Source: OrdinalAnalysis\IDn\PredCutCases\CaseCut.lean (level `k : Fin n` generalised to `k : ℕ`, ID_n -> ID_omega). -/

import OrdinalAnalysis.IDw.PredCutAux
import OrdinalAnalysis.IDw.Elimination

set_option autoImplicit false

namespace OrdinalAnalysis
namespace IDw

open LO LO.FirstOrder
-- case_skeleton: generated header ends here

/-- Case `cut` of `predCut_aux` (generated by case_skeleton.py; statement generated, dispatch=induction; proved). -/
theorem predCut_aux_case_cut
    {A : Semisentence LForm 2}
    {lv : ℕ}
    {μ r : ThetaVNoteD}
    (hμ : ∀ c : ThetaVNoteD, μ ≤ c → c < ThetaVNoteD.Omega lv →
      ∀ j : ℕ, c ≠ ThetaVNoteD.Omega j)
    (hr : r < ThetaVNoteD.Omega lv)
    (ihr : ∀ c : ThetaVNoteD, c < r → PredCutClaim A lv μ c)
    {H : Set ThetaVNoteD → Set ThetaVNoteD}
    {α : ThetaVNoteD}
    {Γ : Sequent (LIinfW)}
    {ψ : Proposition (LIinfW)}
    {α₀ : ThetaVNoteD}
    (p1 : α ∈ H ∅)
    (p2 : paramsVal Γ ⊆ H ∅)
    (p3 : rk ψ < r)
    (p4 : α₀ < α)
    (p5 : IDwDerivable A r H α₀ (ψ :: Γ))
    (p6 : IDwDerivable A r H α₀ (∼ψ :: Γ))
    (ih5 : ThetaVNoteD.NiceS H → ThetaVNoteD.PhiClosed lv H → r ∈ H ∅ → α₀ < ThetaVNoteD.Omega lv →
      IDwDerivable A μ H (ThetaVNoteD.phiN lv r α₀) (ψ :: Γ))
    (ih6 : ThetaVNoteD.NiceS H → ThetaVNoteD.PhiClosed lv H → r ∈ H ∅ → α₀ < ThetaVNoteD.Omega lv →
      IDwDerivable A μ H (ThetaVNoteD.phiN lv r α₀) (∼ψ :: Γ))
    : ThetaVNoteD.NiceS H → ThetaVNoteD.PhiClosed lv H → r ∈ H ∅ → α < ThetaVNoteD.Omega lv →
      IDwDerivable A μ H (ThetaVNoteD.phiN lv r α) Γ := by
  intro hH hP hrH hαΩ
  have hα₀Ω : α₀ < ThetaVNoteD.Omega lv := lt_trans p4 hαΩ
  have e0 := ih5 hH hP hrH hα₀Ω
  have e1 := ih6 hH hP hrH hα₀Ω
  have hφ : ThetaVNoteD.phiN lv r α ∈ H ∅ := hP ∅ r α hr hαΩ hrH p1
  have hφ₀ : ThetaVNoteD.phiN lv r α₀ ∈ H ∅ := hP ∅ r α₀ hr hα₀Ω hrH p5.height_mem
  have hφlt : ThetaVNoteD.phiN lv r α₀ < ThetaVNoteD.phiN lv r α :=
    ThetaVNoteD.phiN_lt_phiN_right hr hα₀Ω hαΩ p4
  rcases lt_or_ge (rk ψ) μ with hlt | hge
  · -- `rk ψ ≺ μ`: the cut stays.
    exact .cut hφ p2 hlt hφlt e0 e1
  · -- `μ ⪯ rk ψ ≺ r`: cut at rank `rk ψ + 1`, Exercise 7.1 (c) down to `rk ψ`, then the outer
    -- induction hypothesis at `rk ψ ≺ r`; `φ(rk ψ, ω^{φ(r,α₀)+1}) ≺ φ(r, α)` by (φ.4).
    have hcΩ : rk ψ < ThetaVNoteD.Omega lv := lt_trans p3 hr
    have hcH : rk ψ ∈ H ∅ :=
      hH.rk_mem_of_noJlevTop
        (rk_lt_OmegaW_iff.mp (lt_trans hcΩ (ThetaVNoteD.Omega_lt_OmegaW lv)))
        (fun s hs => p5.params_head_subset ⟨s, hs, rfl⟩)
    have hprin := ThetaVNoteD.isPrin_phiN (k := lv) hr hαΩ
    have hδH : ThetaVNoteD.succ (ThetaVNoteD.phiN lv r α₀) ∈ H ∅ := hH.succ_mem hφ₀
    have hδlt : ThetaVNoteD.succ (ThetaVNoteD.phiN lv r α₀) < ThetaVNoteD.phiN lv r α :=
      ThetaVNoteD.succ_lt_prin hprin hφlt
    have hc1 : rk ψ < rk ψ + ThetaVNoteD.one := by
      rw [ThetaVNoteD.add_one_eq_succ]; exact ThetaVNoteD.lt_succ _
    have hμc1 : μ ≤ rk ψ + ThetaVNoteD.one := le_trans hge (le_of_lt hc1)
    have D : IDwDerivable A (rk ψ + ThetaVNoteD.one) H
        (ThetaVNoteD.succ (ThetaVNoteD.phiN lv r α₀)) Γ :=
      .cut hδH p2 hc1 (ThetaVNoteD.lt_succ _) (e0.mono_rank hμc1) (e1.mono_rank hμc1)
    have E := IDwDerivable.elimination hH (hμ (rk ψ) hge hcΩ) D
    have hωlt : ThetaVNoteD.omegaPow (ThetaVNoteD.succ (ThetaVNoteD.phiN lv r α₀)) <
        ThetaVNoteD.phiN lv r α :=
      ThetaVNoteD.omegaPow_lt_prin hprin hδlt
    have hωΩ : ThetaVNoteD.omegaPow (ThetaVNoteD.succ (ThetaVNoteD.phiN lv r α₀)) <
        ThetaVNoteD.Omega lv :=
      lt_trans hωlt (ThetaVNoteD.phiN_lt_Omega _ _ _)
    have F := ihr (rk ψ) p3 E hH hP hcH hωΩ
    exact F.mono_height (le_of_lt (ThetaVNoteD.phiN_lt_phiN_left hcΩ hr hωΩ hαΩ p3 hωlt)) hφ
