/- Source: OrdinalAnalysis\IDn\PredCutCases\CaseAll.lean (level `k : Fin n` generalised to `k : ℕ`, ID_n -> ID_omega). -/

import OrdinalAnalysis.IDw.PredCutAux

set_option autoImplicit false

namespace OrdinalAnalysis
namespace IDw

open LO LO.FirstOrder
-- case_skeleton: generated header ends here

/-- Case `all` of `predCut_aux` (generated by case_skeleton.py; statement only, dispatch=induction). -/
theorem predCut_aux_case_all
    {A : Semisentence LForm 2}
    {lv : ℕ}
    {μ r : ThetaVNoteD}
    (hμ : ∀ c : ThetaVNoteD, μ ≤ c → c < ThetaVNoteD.Omega lv →
      ∀ j : ℕ, c ≠ ThetaVNoteD.Omega j)
    (hr : r < ThetaVNoteD.Omega lv)
    (ihr : ∀ c : ThetaVNoteD, c < r → PredCutClaim A lv μ c)
    {H : Set ThetaVNoteD → Set ThetaVNoteD}
    {α : ThetaVNoteD}
    {Γ : Sequent (LIinfW)}
    {φ : Semiproposition (LIinfW) 1}
    (f : ℕ → ThetaVNoteD)
    (p1 : α ∈ H ∅)
    (p2 : paramsVal Γ ⊆ H ∅)
    (p3 : (∀¹ φ) ∈ Γ)
    (p4 : (∀ m, f m < α))
    (p5 : (∀ m, IDwDerivable A r H (f m) (φ/[numI m] :: Γ)))
    (ih5 : ∀ m, ThetaVNoteD.NiceS H → ThetaVNoteD.PhiClosed lv H → r ∈ H ∅ → (f m) < ThetaVNoteD.Omega lv →
      IDwDerivable A μ H (ThetaVNoteD.phiN lv r (f m)) (φ/[numI m] :: Γ))
    : ThetaVNoteD.NiceS H → ThetaVNoteD.PhiClosed lv H → r ∈ H ∅ → α < ThetaVNoteD.Omega lv →
      IDwDerivable A μ H (ThetaVNoteD.phiN lv r α) Γ := by
  intro hH hP hrH hαΩ
  have hφ : ThetaVNoteD.phiN lv r α ∈ H ∅ := hP ∅ r α hr hαΩ hrH p1
  have hfΩ : ∀ m, f m < ThetaVNoteD.Omega lv := fun m => lt_trans (p4 m) hαΩ
  have hf' : ∀ m, ThetaVNoteD.phiN lv r (f m) < ThetaVNoteD.phiN lv r α :=
    fun m => ThetaVNoteD.phiN_lt_phiN_right hr (hfΩ m) hαΩ (p4 m)
  exact .all (fun m => ThetaVNoteD.phiN lv r (f m)) hφ p2 p3 hf'
    (fun m => ih5 m hH hP hrH (hfΩ m))
