/- Source: OrdinalAnalysis\IDn\PredCutCases\CaseStage.lean (level `k : Fin n` generalised to `k : ℕ`, ID_n -> ID_omega). -/

import OrdinalAnalysis.IDw.PredCutAux

set_option autoImplicit false

namespace OrdinalAnalysis
namespace IDw

open LO LO.FirstOrder
-- case_skeleton: generated header ends here

/-- Case `stage` of `predCut_aux` (generated by case_skeleton.py; statement only, dispatch=induction). -/
theorem predCut_aux_case_stage
    {A : Semisentence LForm 2}
    {lv : ℕ}
    {μ r : ThetaVNoteD}
    (hμ : ∀ c : ThetaVNoteD, μ ≤ c → c < ThetaVNoteD.Omega lv →
      ∀ j : ℕ, c ≠ ThetaVNoteD.Omega j)
    (hr : r < ThetaVNoteD.Omega lv)
    (ihr : ∀ c : ThetaVNoteD, c < r → PredCutClaim A lv μ c)
    {H : Set ThetaVNoteD → Set ThetaVNoteD}
    {α : ThetaVNoteD}
    {Γ : Sequent (LIinfW)}
    {k : ℕ}
    {a : StageAt k}
    {t : SyntacticTerm (LIinfW)}
    (g : StageAt k)
    {α₀ : ThetaVNoteD}
    (p1 : α ∈ H ∅)
    (p2 : paramsVal Γ ⊆ H ∅)
    (p3 : stageAt (⟨k, a⟩ : Stage) t ∈ Γ)
    (p4 : g.1 < a.1)
    (p5 : g.1 < α)
    (p6 : g.1 ∈ H ∅)
    (p7 : α₀ < α)
    (p8 : IDwDerivable A r H α₀ (unfoldW A k g t :: Γ))
    (ih8 : ThetaVNoteD.NiceS H → ThetaVNoteD.PhiClosed lv H → r ∈ H ∅ → α₀ < ThetaVNoteD.Omega lv →
      IDwDerivable A μ H (ThetaVNoteD.phiN lv r α₀) (unfoldW A k g t :: Γ))
    : ThetaVNoteD.NiceS H → ThetaVNoteD.PhiClosed lv H → r ∈ H ∅ → α < ThetaVNoteD.Omega lv →
      IDwDerivable A μ H (ThetaVNoteD.phiN lv r α) Γ := by
  intro hH hP hrH hαΩ
  have hα₀Ω : α₀ < ThetaVNoteD.Omega lv := lt_trans p7 hαΩ
  have hφ : ThetaVNoteD.phiN lv r α ∈ H ∅ := hP ∅ r α hr hαΩ hrH p1
  have hglt : g.1 < ThetaVNoteD.phiN lv r α :=
    lt_trans p5 (ThetaVNoteD.lt_phiN_self hr hαΩ)
  have hα₀lt : ThetaVNoteD.phiN lv r α₀ < ThetaVNoteD.phiN lv r α :=
    ThetaVNoteD.phiN_lt_phiN_right hr hα₀Ω hαΩ p7
  exact .stage g hφ p2 p3 p4 hglt p6 hα₀lt (ih8 hH hP hrH hα₀Ω)
