/- Source: OrdinalAnalysis\IDn\PredCutCases\CaseOrR.lean (level `k : Fin n` generalised to `k : ℕ`, ID_n -> ID_omega). -/

import OrdinalAnalysis.IDw.PredCutAux

set_option autoImplicit false

namespace OrdinalAnalysis
namespace IDw

open LO LO.FirstOrder
-- case_skeleton: generated header ends here

/-- Case `orR` of `predCut_aux` (generated by case_skeleton.py; statement only, dispatch=induction). -/
theorem predCut_aux_case_orR
    {A : Semisentence LForm 2}
    {lv : ℕ}
    {μ r : ThetaVNoteD}
    (hμ : ∀ c : ThetaVNoteD, μ ≤ c → c < ThetaVNoteD.Omega lv →
      ∀ j : ℕ, c ≠ ThetaVNoteD.Omega j)
    (hr : r < ThetaVNoteD.Omega lv)
    (ihr : ∀ c : ThetaVNoteD, c < r → PredCutClaim A lv μ c)
    {H : Set ThetaVNoteD → Set ThetaVNoteD}
    {α : ThetaVNoteD}
    {Γ : Sequent (LIinfW)}
    {φ ψ : Proposition (LIinfW)}
    {α₀ : ThetaVNoteD}
    (p1 : α ∈ H ∅)
    (p2 : paramsVal Γ ⊆ H ∅)
    (p3 : φ ⋎ ψ ∈ Γ)
    (p4 : ThetaVNoteD.one < α)
    (p5 : α₀ < α)
    (p6 : IDwDerivable A r H α₀ (ψ :: Γ))
    (ih6 : ThetaVNoteD.NiceS H → ThetaVNoteD.PhiClosed lv H → r ∈ H ∅ → α₀ < ThetaVNoteD.Omega lv →
      IDwDerivable A μ H (ThetaVNoteD.phiN lv r α₀) (ψ :: Γ))
    : ThetaVNoteD.NiceS H → ThetaVNoteD.PhiClosed lv H → r ∈ H ∅ → α < ThetaVNoteD.Omega lv →
      IDwDerivable A μ H (ThetaVNoteD.phiN lv r α) Γ := by
  intro hH hP hrH hαΩ
  have hα₀Ω : α₀ < ThetaVNoteD.Omega lv := lt_trans p5 hαΩ
  have hφ : ThetaVNoteD.phiN lv r α ∈ H ∅ := hP ∅ r α hr hαΩ hrH p1
  have h1 : ThetaVNoteD.one < ThetaVNoteD.phiN lv r α :=
    lt_trans p4 (ThetaVNoteD.lt_phiN_self hr hαΩ)
  have h0 : ThetaVNoteD.phiN lv r α₀ < ThetaVNoteD.phiN lv r α :=
    ThetaVNoteD.phiN_lt_phiN_right hr hα₀Ω hαΩ p5
  exact .orR hφ p2 p3 h1 h0 (ih6 hH hP hrH hα₀Ω)
