/-
  Δ₀-formulas of `ℒ_Ad` and relativisation `A^u` (Buchholz 1992, §1 p.3).

  B92: "A quantifier occurrence `∀x [∃x]` in a formula `A` is called *restricted* if its range is
  of the form `x ∈ v → B(x)` [`x ∈ v ∧ B(x)`] with `x ≢ v`.  A formula `A` is called a
  Δ₀-formula if it contains no unrestricted quantifier."  `Ad` atoms are allowed.  "The formula
  obtained from `A` by restricting every unrestricted quantifier to `u` is denoted `A^u`."

  In Foundation's negation normal form the restricted quantifiers are exactly `ballAt`/`bexAt`,
  so `IsDelta0` is the inductive predicate generated by the atoms, `⋏`, `⋎`, `ballAt`, `bexAt`.
  Conversely `relAt` recognises the restricted-quantifier *shape* (`∀¹ (∼(#0 ∈ v) ⋎ B)` with
  `v ≠ #0`, resp. `∃¹ (#0 ∈ v ⋏ B)`), keeps such a quantifier and recurses into `B`, and
  relativises every other quantifier.  `relAt_of_isDelta0` (relativisation fixes Δ₀-formulas) is
  the sanity check that the two notions agree.

  Contents.

    `IsDelta0`                                    the predicate
    `IsDelta0.neg/and/or/imp/iff/ball/bex/…`      closure lemmas
    `IsDelta0.rew`, `.subst`, `.shift`, …         closure under rewriting / substitution
    `relAt`                                       `A^u`
    `relAt_ballAt`, `relAt_bexAt`, `relAt_of_isDelta0`
-/
import OrdinalAnalysis.KPi.Language

set_option autoImplicit false

namespace OrdinalAnalysis

namespace KPi

open LO LO.FirstOrder

variable {ξ ξ₁ ξ₂ : Type*} {n n₁ n₂ : ℕ}

/-! ### The Δ₀ predicate -/

/-- **Δ₀-formulas of `ℒ_Ad`** (B92 p.3): no unrestricted quantifier; atoms `s ∈ t`, `s ∉ t`,
`Ad t`, `¬Ad t`; closed under `⋏`, `⋎` and the restricted quantifiers `∀x∈t`, `∃x∈t`. -/
inductive IsDelta0 {ξ : Type*} : {n : ℕ} → Semiformula LAd ξ n → Prop
  | verum {n : ℕ} : IsDelta0 (⊤ : Semiformula LAd ξ n)
  | falsum {n : ℕ} : IsDelta0 (⊥ : Semiformula LAd ξ n)
  | mem {n : ℕ} (s t : Semiterm LAd ξ n) : IsDelta0 (memAt s t)
  | nmem {n : ℕ} (s t : Semiterm LAd ξ n) : IsDelta0 (nmemAt s t)
  | ad {n : ℕ} (t : Semiterm LAd ξ n) : IsDelta0 (adAt t)
  | nad {n : ℕ} (t : Semiterm LAd ξ n) : IsDelta0 (nadAt t)
  | and {n : ℕ} {φ ψ : Semiformula LAd ξ n} : IsDelta0 φ → IsDelta0 ψ → IsDelta0 (φ ⋏ ψ)
  | or {n : ℕ} {φ ψ : Semiformula LAd ξ n} : IsDelta0 φ → IsDelta0 ψ → IsDelta0 (φ ⋎ ψ)
  | ball {n : ℕ} (t : Semiterm LAd ξ n) {φ : Semiformula LAd ξ (n + 1)} :
      IsDelta0 φ → IsDelta0 (ballAt t φ)
  | bex {n : ℕ} (t : Semiterm LAd ξ n) {φ : Semiformula LAd ξ (n + 1)} :
      IsDelta0 φ → IsDelta0 (bexAt t φ)

namespace IsDelta0

attribute [simp] IsDelta0.verum IsDelta0.falsum IsDelta0.mem IsDelta0.nmem IsDelta0.ad IsDelta0.nad

/-- Closure under negation (de Morgan dualisation; `∼(∀x∈t φ) = ∃x∈t ∼φ`). -/
theorem neg {φ : Semiformula LAd ξ n} (h : IsDelta0 φ) : IsDelta0 (∼φ) := by
  induction h with
  | verum => exact IsDelta0.falsum
  | falsum => exact IsDelta0.verum
  | mem s t => exact IsDelta0.nmem s t
  | nmem s t => exact IsDelta0.mem s t
  | ad t => exact IsDelta0.nad t
  | nad t => exact IsDelta0.ad t
  | and _ _ ih₁ ih₂ => exact IsDelta0.or ih₁ ih₂
  | or _ _ ih₁ ih₂ => exact IsDelta0.and ih₁ ih₂
  | ball t _ ih => exact IsDelta0.bex t ih
  | bex t _ ih => exact IsDelta0.ball t ih

theorem of_neg {φ : Semiformula LAd ξ n} (h : IsDelta0 (∼φ)) : IsDelta0 φ := by
  simpa using h.neg

@[simp] theorem neg_iff {φ : Semiformula LAd ξ n} : IsDelta0 (∼φ) ↔ IsDelta0 φ :=
  ⟨of_neg, neg⟩

/-- Closure under implication `φ 🡒 ψ := ∼φ ⋎ ψ`. -/
theorem imp {φ ψ : Semiformula LAd ξ n} (hφ : IsDelta0 φ) (hψ : IsDelta0 ψ) :
    IsDelta0 (φ 🡒 ψ) := IsDelta0.or hφ.neg hψ

/-- Closure under biconditional. -/
theorem iff {φ ψ : Semiformula LAd ξ n} (hφ : IsDelta0 φ) (hψ : IsDelta0 ψ) :
    IsDelta0 (φ 🡘 ψ) := IsDelta0.and (hφ.imp hψ) (hψ.imp hφ)

/-- `∀x∈t φ` in Foundation's own `ballMem` form. -/
theorem ballMem (t : Semiterm LAd ξ n) {φ : Semiformula LAd ξ (n + 1)} (h : IsDelta0 φ) :
    IsDelta0 (Semiformula.ballMem t φ) := by
  rw [← ballAt_eq_ballMem]; exact IsDelta0.ball t h

theorem bexsMem (t : Semiterm LAd ξ n) {φ : Semiformula LAd ξ (n + 1)} (h : IsDelta0 φ) :
    IsDelta0 (Semiformula.bexsMem t φ) := by
  rw [← bexAt_eq_bexsMem]; exact IsDelta0.bex t h

/-- Bounded quantifier over a bounded quantifier: the shape `∀x∈t ∃y∈x φ`. -/
theorem ball_bex (t : Semiterm LAd ξ n) {φ : Semiformula LAd ξ (n + 2)} (h : IsDelta0 φ) :
    IsDelta0 (ballAt t (bexAt #0 φ)) := IsDelta0.ball t (IsDelta0.bex _ h)

theorem subsetAt (u v : Semiterm LAd ξ n) : IsDelta0 (KPi.subsetAt u v) :=
  IsDelta0.ball u (IsDelta0.mem _ _)

theorem eqAt (u v : Semiterm LAd ξ n) : IsDelta0 (KPi.eqAt u v) :=
  IsDelta0.and (subsetAt u v) (subsetAt v u)

theorem tranAt (u : Semiterm LAd ξ n) : IsDelta0 (KPi.tranAt u) :=
  IsDelta0.ball u (IsDelta0.ball _ (IsDelta0.mem _ _))

theorem infiniteAt (u : Semiterm LAd ξ n) : IsDelta0 (KPi.infiniteAt u) :=
  IsDelta0.and (IsDelta0.bex u (subsetAt _ _))
    (IsDelta0.ball u (IsDelta0.bex _ (IsDelta0.mem _ _)))

/-! #### Closure under rewriting -/

/-- Rewriting commutes with restricted quantifiers: `ω (∀x∈t φ) = ∀x∈ω t (ω.q φ)`. -/
theorem rew_ballAt (ω : Rew LAd ξ₁ n₁ ξ₂ n₂) (t : Semiterm LAd ξ₁ n₁)
    (φ : Semiformula LAd ξ₁ (n₁ + 1)) : ω ▹ ballAt t φ = ballAt (ω t) (ω.q ▹ φ) := by
  simp [ballAt, nmemAt]

theorem rew_bexAt (ω : Rew LAd ξ₁ n₁ ξ₂ n₂) (t : Semiterm LAd ξ₁ n₁)
    (φ : Semiformula LAd ξ₁ (n₁ + 1)) : ω ▹ bexAt t φ = bexAt (ω t) (ω.q ▹ φ) := by
  simp [bexAt, memAt]

theorem rew_memAt (ω : Rew LAd ξ₁ n₁ ξ₂ n₂) (s t : Semiterm LAd ξ₁ n₁) :
    ω ▹ memAt s t = memAt (ω s) (ω t) := by simp [memAt]

theorem rew_nmemAt (ω : Rew LAd ξ₁ n₁ ξ₂ n₂) (s t : Semiterm LAd ξ₁ n₁) :
    ω ▹ nmemAt s t = nmemAt (ω s) (ω t) := by simp [nmemAt]

theorem rew_adAt (ω : Rew LAd ξ₁ n₁ ξ₂ n₂) (t : Semiterm LAd ξ₁ n₁) :
    ω ▹ adAt t = adAt (ω t) := by simp [adAt]

theorem rew_nadAt (ω : Rew LAd ξ₁ n₁ ξ₂ n₂) (t : Semiterm LAd ξ₁ n₁) :
    ω ▹ nadAt t = nadAt (ω t) := by simp [nadAt]

/-- **Δ₀ is closed under every rewriting** (in particular under substitution of terms for
variables, shifting, `free`, `fix`, embedding of sentences): rewriting preserves the shape of
restricted quantifiers because `Rew.q` commutes with `Rew.bShift`. -/
theorem rew {φ : Semiformula LAd ξ₁ n₁} (h : IsDelta0 φ) (ω : Rew LAd ξ₁ n₁ ξ₂ n₂) :
    IsDelta0 (ω ▹ φ) := by
  induction h generalizing n₂ with
  | verum => simp
  | falsum => simp
  | mem s t => rw [rew_memAt]; exact IsDelta0.mem _ _
  | nmem s t => rw [rew_nmemAt]; exact IsDelta0.nmem _ _
  | ad t => rw [rew_adAt]; exact IsDelta0.ad _
  | nad t => rw [rew_nadAt]; exact IsDelta0.nad _
  | and _ _ ih₁ ih₂ => simpa using IsDelta0.and (ih₁ ω) (ih₂ ω)
  | or _ _ ih₁ ih₂ => simpa using IsDelta0.or (ih₁ ω) (ih₂ ω)
  | ball t _ ih => rw [rew_ballAt]; exact IsDelta0.ball _ (ih ω.q)
  | bex t _ ih => rw [rew_bexAt]; exact IsDelta0.bex _ (ih ω.q)

/-- Substitution of terms for the bound variables. -/
theorem subst {k : ℕ} {φ : Semiformula LAd ξ k} (h : IsDelta0 φ) (w : Fin k → Semiterm LAd ξ n) :
    IsDelta0 (φ ⇜ w) := h.rew _

/-- The one-variable substitution `φ/[t]` used by the axiom schemata. -/
theorem subst₁ {φ : Semiformula LAd ξ 1} (h : IsDelta0 φ) (t : Semiterm LAd ξ n) :
    IsDelta0 (φ/[t]) := h.subst _

theorem bShift {φ : Semiformula LAd ξ n} (h : IsDelta0 φ) : IsDelta0 (Rew.bShift ▹ φ) := h.rew _

theorem shift {φ : Semiformula LAd ℕ n} (h : IsDelta0 φ) : IsDelta0 (Rewriting.shift φ) := h.rew _

theorem free {φ : Semiformula LAd ℕ (n + 1)} (h : IsDelta0 φ) : IsDelta0 (Rewriting.free φ) :=
  h.rew _

theorem fix {φ : Semiformula LAd ℕ n} (h : IsDelta0 φ) : IsDelta0 (Rewriting.fix φ) := h.rew _

theorem emb {ο : Type*} [IsEmpty ο] {φ : Semiformula LAd ο n} (h : IsDelta0 φ) :
    IsDelta0 (Rewriting.emb (ξ := ξ) φ) := h.rew _

theorem rewriteMap {φ : Semiformula LAd ξ₁ n} (h : IsDelta0 φ) (e : ξ₁ → ξ₂) :
    IsDelta0 (Rew.rewriteMap e ▹ φ) := h.rew _

end IsDelta0

/-! ### Relativisation `A^u` -/

/-- `isBv0 t`: is `t` literally the innermost bound variable `#0`?  (Decides the side condition
`x ≢ v` of a restricted quantifier.) -/
def isBv0 {ξ : Type*} {n : ℕ} : Semiterm LAd ξ (n + 1) → Bool
  | .bvar i => decide (i = 0)
  | .fvar _ => false
  | .func f _ => Empty.elim f

/-- **`A^u`** (B92 p.3): restrict every UNRESTRICTED quantifier of `A` to `u`.  A quantifier is
restricted iff its range has the shape `#0 ∉ v ∨ B` (resp. `#0 ∈ v ∧ B`) with `v ≠ #0`; such a
quantifier is kept and `B` is relativised; any other `∀x φ` becomes `∀x (x ∉ u ∨ φ^u)` and any
other `∃x φ` becomes `∃x (x ∈ u ∧ φ^u)`. -/
def relAt {ξ : Type*} : {n : ℕ} → Semiterm LAd ξ n → Semiformula LAd ξ n → Semiformula LAd ξ n
  | _, _, .verum => ⊤
  | _, _, .falsum => ⊥
  | _, _, .rel r v => .rel r v
  | _, _, .nrel r v => .nrel r v
  | _, u, .and φ ψ => relAt u φ ⋏ relAt u ψ
  | _, u, .or φ ψ => relAt u φ ⋎ relAt u ψ
  | _, u, .all (.or (.nrel AdRel.mem v) B) =>
      if isBv0 (v 0) && !isBv0 (v 1) then
        ∀¹ (.nrel AdRel.mem v ⋎ relAt (Rew.bShift u) B)
      else
        ∀¹ (nmemAt #0 (Rew.bShift u) ⋎ (.nrel AdRel.mem v ⋎ relAt (Rew.bShift u) B))
  | _, u, .all φ => ∀¹ (nmemAt #0 (Rew.bShift u) ⋎ relAt (Rew.bShift u) φ)
  | _, u, .exs (.and (.rel AdRel.mem v) B) =>
      if isBv0 (v 0) && !isBv0 (v 1) then
        ∃¹ (.rel AdRel.mem v ⋏ relAt (Rew.bShift u) B)
      else
        ∃¹ (memAt #0 (Rew.bShift u) ⋏ (.rel AdRel.mem v ⋏ relAt (Rew.bShift u) B))
  | _, u, .exs φ => ∃¹ (memAt #0 (Rew.bShift u) ⋏ relAt (Rew.bShift u) φ)

/-! #### Relativisation: the restricted-quantifier shape is recognised -/

/-- A shifted term is never the innermost bound variable. -/
theorem isBv0_bShift {ξ : Type*} {n : ℕ} (t : Semiterm LAd ξ n) : isBv0 (Rew.bShift t) = false := by
  cases t with
  | bvar i => simp [isBv0]
  | fvar x => simp [isBv0]
  | func f _ => exact Empty.elim f

@[simp] theorem isBv0_bvar_zero {ξ : Type*} {n : ℕ} : isBv0 (#0 : Semiterm LAd ξ (n + 1)) = true := by
  simp [isBv0]

section relAt

variable {ξ : Type*} {n : ℕ}

@[simp] theorem relAt_verum (u : Semiterm LAd ξ n) : relAt u ⊤ = ⊤ := rfl
@[simp] theorem relAt_falsum (u : Semiterm LAd ξ n) : relAt u ⊥ = ⊥ := rfl
@[simp] theorem relAt_and (u : Semiterm LAd ξ n) (φ ψ : Semiformula LAd ξ n) :
    relAt u (φ ⋏ ψ) = relAt u φ ⋏ relAt u ψ := rfl
@[simp] theorem relAt_or (u : Semiterm LAd ξ n) (φ ψ : Semiformula LAd ξ n) :
    relAt u (φ ⋎ ψ) = relAt u φ ⋎ relAt u ψ := rfl
@[simp] theorem relAt_memAt (u s t : Semiterm LAd ξ n) : relAt u (memAt s t) = memAt s t := rfl
@[simp] theorem relAt_nmemAt (u s t : Semiterm LAd ξ n) : relAt u (nmemAt s t) = nmemAt s t := rfl
@[simp] theorem relAt_adAt (u t : Semiterm LAd ξ n) : relAt u (adAt t) = adAt t := rfl
@[simp] theorem relAt_nadAt (u t : Semiterm LAd ξ n) : relAt u (nadAt t) = nadAt t := rfl

/-- A restricted universal quantifier is kept; only its range `B` is relativised. -/
@[simp] theorem relAt_ballAt (u t : Semiterm LAd ξ n) (φ : Semiformula LAd ξ (n + 1)) :
    relAt u (ballAt t φ) = ballAt t (relAt (Rew.bShift u) φ) := by
  have hb : (isBv0 ((![#0, Rew.bShift t] : Fin 2 → Semiterm LAd ξ (n + 1)) 0) &&
      !isBv0 ((![#0, Rew.bShift t] : Fin 2 → Semiterm LAd ξ (n + 1)) 1)) = true := by
    simp [isBv0_bShift]
  exact (if_pos hb).trans rfl

/-- A restricted existential quantifier is kept; only its range `B` is relativised. -/
@[simp] theorem relAt_bexAt (u t : Semiterm LAd ξ n) (φ : Semiformula LAd ξ (n + 1)) :
    relAt u (bexAt t φ) = bexAt t (relAt (Rew.bShift u) φ) := by
  have hb : (isBv0 ((![#0, Rew.bShift t] : Fin 2 → Semiterm LAd ξ (n + 1)) 0) &&
      !isBv0 ((![#0, Rew.bShift t] : Fin 2 → Semiterm LAd ξ (n + 1)) 1)) = true := by
    simp [isBv0_bShift]
  exact (if_pos hb).trans rfl

/-- An unrestricted `∀x φ` (its range is not a restricted-quantifier shape, here: `φ` is the
range of an arbitrary universal whose range is an atom-free conjunction) becomes `∀x∈u φ^u`:
the generic case, stated for a range that is a conjunction. -/
theorem relAt_all_and (u : Semiterm LAd ξ n) (φ ψ : Semiformula LAd ξ (n + 1)) :
    relAt u (∀¹ (φ ⋏ ψ)) = ballAt u (relAt (Rew.bShift u) φ ⋏ relAt (Rew.bShift u) ψ) := rfl

/-- **Relativisation fixes Δ₀-formulas** (all their quantifiers are restricted): `A^u = A`. -/
theorem relAt_of_isDelta0 {φ : Semiformula LAd ξ n} (h : IsDelta0 φ) (u : Semiterm LAd ξ n) :
    relAt u φ = φ := by
  induction h with
  | verum => rfl
  | falsum => rfl
  | mem s t => rfl
  | nmem s t => rfl
  | ad t => rfl
  | nad t => rfl
  | and _ _ ih₁ ih₂ => simp [ih₁, ih₂]
  | or _ _ ih₁ ih₂ => simp [ih₁, ih₂]
  | ball t _ ih => rw [relAt_ballAt, ih]
  | bex t _ ih => rw [relAt_bexAt, ih]

end relAt

end KPi

end OrdinalAnalysis
