/-
  One level-free hull `C(α, β)` and one operator `H_α` for all levels of the multi-level
  ϑ-notation.

  Sources: W. Buchholz, *A simplified version of local predicativity* (1992), Definition 4.2
  (one set `C(α, β)` closed under every collapsing function restricted to arguments `< α`,
  `C_κ(α) = C(α, Ω_κ)`); G. Wilken, arXiv:2410.15953, Definition 2.7 (the hulls `C̄_i(α, β)`
  closed under `ϑ̄_j` on arguments in `dom(ϑ̄_j) ∩ α`) and Lemma 2.13 (`dom(ϑ̄_m)` is
  `K*_{m+1}(α) < α`, here `ThetaW/Dom.dom_theta_iff`); A. Freund, arXiv:2204.09321,
  Definition 3.8, Proposition 3.9, Definition 3.10, Proposition 3.11, Definition 5.4,
  Exercise 5.5 for the one-level version (`Ordinal/Theta/Hull.lean`).

  `CsetS a b` is generated by: every `Ω_j`; every `γ ≺ β`; `ϑ_j ξ` for **every** level `j`
  when `ξ` is in the hull, `ξ ≺ α` and `ϑ_j ξ` is in the domain; sums.  No clause mentions a
  level, so there is one hull and one operator `HopS a` for all levels.  The level `k` enters
  only through the second argument `β` (in `(Ω_k, Ω_{k+1})` for the level-`k` uses) and through
  the per-level hull hypothesis `HullHypS k`.

  Proved here (level `k` arbitrary in each):
  * Proposition 3.9 at every level: `theta_isLeastS k` (`ϑ_k α` is the least `γ` with
    `C(α, γ) ∩ Ω_{k+1} ≺* γ` and `α ∈ C(α, γ)`).  The lower collapses `ϑ_j γ` (`j < k`) enter
    the hull through the clause `γ ≺ β`: `Ω_k` (Lean `Omega (k-1)`) is a hull member below
    `Ω_{k+1}`, so it lies below every candidate `γ`.  The higher collapses inside an own-level
    argument `ξ` have their arguments in `G_k(ξ)`, which the domain condition bounds by
    `ξ ≺ α` (`CsetS.of_E_G`).
  * Proposition 3.11 (a)–(c) and the hull hypothesis facts, for the one operator `HopS`.
  * `HopS a` is nice for the all-level atomic support `Atoms` (`ThetaWNoteD.NiceS`), hence
    closed under `+`, `⊕`, `ω^·`, `ω ·`, successor; `adjoin` keeps niceness.
  `HullDom.lean` proves the domain lemma `dom_add_omegaPow` on top of this file.
-/
import OrdinalAnalysis.Ordinal.ThetaW.Hull

set_option autoImplicit false

namespace OrdinalAnalysis

namespace ThetaWTerm

/-! ### The all-level atomic support -/

mutual
/-- `Atoms(α)`: the maximal collapse subterms of `α`, of every level, looking only through
Cantor sums (`E_k` for `k` above every level of `α`). -/
def Atoms : ThetaWTerm → List ThetaWTerm
  | Omega _ => []
  | theta j a => [theta j a]
  | sum xs => AtomsList xs
/-- The union of the `Atoms(α_i)` over a list. -/
def AtomsList : List ThetaWTerm → List ThetaWTerm
  | [] => []
  | x :: xs => Atoms x ++ AtomsList xs
end

@[simp] theorem Atoms_Omega (j : ℕ) : Atoms (Omega j) = [] := by simp [Atoms]

@[simp] theorem Atoms_theta (j : ℕ) (a : ThetaWTerm) : Atoms (theta j a) = [theta j a] := by
  simp [Atoms]

@[simp] theorem Atoms_nil : Atoms (sum []) = [] := by simp [Atoms, AtomsList]

@[simp] theorem Atoms_cons (x : ThetaWTerm) (xs : List ThetaWTerm) :
    Atoms (sum (x :: xs)) = Atoms x ++ Atoms (sum xs) := by simp [Atoms, AtomsList]

theorem mem_Atoms_sum {g : ThetaWTerm} {xs : List ThetaWTerm} :
    g ∈ Atoms (sum xs) ↔ ∃ x ∈ xs, g ∈ Atoms x := by
  induction xs with
  | nil => simp
  | cons y ys ih => simp [ih]

theorem mem_Atoms_ofList {g : ThetaWTerm} {xs : List ThetaWTerm} :
    g ∈ Atoms (ofList xs) ↔ ∃ x ∈ xs, g ∈ Atoms x := by
  match xs with
  | [] => simp
  | [x] =>
    by_cases h : IsPrin x
    · rw [ofList_singleton_prin h]; simp
    · rw [ofList_singleton_not_prin h]; exact mem_Atoms_sum
  | _ :: _ :: _ => exact mem_Atoms_sum

theorem mem_Atoms_iff_toList {t g : ThetaWTerm} :
    g ∈ Atoms t ↔ ∃ e ∈ toList t, g ∈ Atoms e := by
  cases t with
  | Omega j => simp [toList]
  | theta j a => simp [toList]
  | sum xs => exact mem_Atoms_sum

theorem mem_Atoms_of_mem_Atoms_onePlus {e g : ThetaWTerm} (h : g ∈ Atoms (onePlus e)) :
    g ∈ Atoms e := by
  unfold onePlus at h
  obtain ⟨x, hx, hg⟩ := mem_Atoms_ofList.mp h
  rcases mem_addL hx with hx | hx
  · rw [List.mem_singleton.mp hx] at hg; simp at hg
  · exact mem_Atoms_iff_toList.mpr ⟨x, hx, hg⟩

/-- For normal `α`, every atom of `α` is `≼ α`. -/
theorem le_of_mem_Atoms : ∀ {a g : ThetaWTerm}, NF a → g ∈ Atoms a → g ≤ a
  | Omega _, _, _, h => by simp at h
  | theta j a, g, _, h => by simp at h; exact Or.inr h
  | sum xs, g, ha, h => by
    obtain ⟨y, hy, hg⟩ := mem_Atoms_sum.mp h
    have h1 := le_of_mem_Atoms (ha.of_mem hy) hg
    cases xs with
    | nil => cases hy
    | cons x xs =>
      have h2 := ha.desc.le_head y hy
      exact Or.inl (lt_of_le_of_lt' (le_trans' h1 h2) (lt_sum_cons_self x xs))
termination_by a => l a
decreasing_by exact l_lt_of_mem hy

theorem NF.of_mem_Atoms : ∀ {a g : ThetaWTerm}, NF a → g ∈ Atoms a → NF g
  | Omega _, _, _, h => by simp at h
  | theta j a, g, ha, h => by simp at h; exact h ▸ ha
  | sum xs, g, ha, h => by
    obtain ⟨y, hy, hg⟩ := mem_Atoms_sum.mp h
    exact NF.of_mem_Atoms (ha.of_mem hy) hg
termination_by a => l a
decreasing_by exact l_lt_of_mem hy

theorem Dom.of_mem_Atoms : ∀ {a g : ThetaWTerm}, Dom a → g ∈ Atoms a → Dom g
  | Omega _, _, _, h => by simp at h
  | theta j a, g, ha, h => by simp at h; exact h ▸ ha
  | sum xs, g, ha, h => by
    obtain ⟨y, hy, hg⟩ := mem_Atoms_sum.mp h
    exact Dom.of_mem_Atoms (ha.of_mem hy) hg
termination_by a => l a
decreasing_by exact l_lt_of_mem hy

/-! ### The level-free hull `C(α, β)` on raw terms -/

/-- The generating clauses of the level-free hull `C(α, β)` (Buchholz 1992, Definition 4.2;
Wilken, Definition 2.7): no clause mentions a level. -/
inductive CsetS (a b : ThetaWTerm) : ThetaWTerm → Prop
  /-- `Ω_j ∈ C(α, β)` for every level `j`. -/
  | ofOmega (j : ℕ) : CsetS a b (Omega j)
  /-- `γ ∈ C(α, β)` for `γ ≺ β`. -/
  | ofLt {g : ThetaWTerm} : g < b → CsetS a b g
  /-- `ξ ∈ C(α, β)`, `ξ ≺ α` and `ϑ_j ξ` in the domain give `ϑ_j ξ ∈ C(α, β)`, every `j`. -/
  | ofTheta {j : ℕ} {g : ThetaWTerm} : CsetS a b g → g < a → Dom (theta j g) →
      CsetS a b (theta j g)
  /-- `⟨γ₀, …, γ_{n-1}⟩ ∈ C(α, β)` when every `γ_i ∈ C(α, β)`. -/
  | ofSum {xs : List ThetaWTerm} : (∀ x ∈ xs, CsetS a b x) → CsetS a b (sum xs)

/-- Niceness for the atomic support, right to left. -/
theorem CsetS.of_Atoms {a b : ThetaWTerm} : ∀ {g : ThetaWTerm},
    (∀ d ∈ Atoms g, CsetS a b d) → CsetS a b g
  | Omega j, _ => .ofOmega j
  | theta j a', h => h _ (by simp)
  | sum xs, h => .ofSum fun x hx => CsetS.of_Atoms (fun d hd => h d (mem_Atoms_sum.mpr ⟨x, hx, hd⟩))
termination_by g => l g
decreasing_by exact l_lt_of_mem hx

/-- Niceness for the atomic support, left to right. -/
theorem CsetS.Atoms_sub {a b g : ThetaWTerm} (h : CsetS a b g) (hg : NF g) :
    ∀ d ∈ Atoms g, CsetS a b d := by
  revert hg
  induction h with
  | ofOmega j => intro _ d hd; simp at hd
  | ofLt hlt =>
    intro hg d hd
    exact .ofLt (lt_of_le_of_lt' (le_of_mem_Atoms hg hd) hlt)
  | ofTheta hc hlt hdom _ =>
    intro _ d hd
    simp only [Atoms_theta, List.mem_singleton] at hd
    subst hd
    exact .ofTheta hc hlt hdom
  | ofSum _ ih =>
    intro hg d hd
    obtain ⟨x, hx, hdx⟩ := mem_Atoms_sum.mp hd
    exact ih x hx (hg.of_mem hx) d hdx

theorem CsetS.iff_Atoms {a b g : ThetaWTerm} (hg : NF g) :
    CsetS a b g ↔ ∀ d ∈ Atoms g, CsetS a b d :=
  ⟨fun h => h.Atoms_sub hg, CsetS.of_Atoms⟩

/-- The level-`k` coefficients of a hull member are hull members (Proposition 3.9, the half
that survives: the hull is closed downward along `E_k`). -/
theorem CsetS.E_sub (k : ℕ) {a b g : ThetaWTerm} (h : CsetS a b g) (hg : NF g) :
    ∀ d ∈ E k g, CsetS a b d := by
  revert hg
  induction h with
  | ofOmega j => intro _ d hd; simp at hd
  | ofLt hlt =>
    intro hg d hd
    exact .ofLt (lt_of_le_of_lt' (le_of_mem_E hg hd) hlt)
  | @ofTheta j g hc hlt hdom ih =>
    intro hg d hd
    by_cases hj : j ≤ k
    · rw [E_theta_of_le hj] at hd
      simp only [List.mem_singleton] at hd
      subst hd
      exact .ofTheta hc hlt hdom
    · rw [E_theta_of_lt (Nat.lt_of_not_le hj)] at hd
      exact ih hg.theta_arg d hd
  | ofSum _ ih =>
    intro hg d hd
    obtain ⟨x, hx, hdx⟩ := mem_E_sum.mp hd
    exact ih x hx (hg.of_mem hx) d hdx

/-- The converse, with the price the level-free hull charges: a domain term whose level-`k`
coefficients lie in `C(α, β)` and whose `G_k`-arguments lie below `α` is in `C(α, β)`. -/
theorem CsetS.of_E_G (k : ℕ) {a b : ThetaWTerm} : ∀ {g : ThetaWTerm}, Dom g →
    (∀ d ∈ E k g, CsetS a b d) → (∀ y ∈ G k g, y < a) → CsetS a b g
  | Omega j, _, _, _ => .ofOmega j
  | theta j a', hd, hE, hG => by
      by_cases hj : j ≤ k
      · exact hE _ (by simp [E_theta_of_le hj])
      · have hjk : k < j := Nat.lt_of_not_le hj
        rw [E_theta_of_lt hjk] at hE
        rw [G_theta_of_lt hjk] at hG
        exact .ofTheta
          (CsetS.of_E_G k hd.theta_arg hE fun y hy => hG y (List.mem_cons_of_mem _ hy))
          (hG a' List.mem_cons_self) hd
  | sum xs, hd, hE, hG =>
      .ofSum fun x hx => CsetS.of_E_G k (hd.of_mem hx)
        (fun d hdx => hE d (mem_E_of_mem hx hdx))
        (fun y hy => hG y (mem_G_sum.mpr ⟨x, hx, hy⟩))
termination_by g => l g
decreasing_by
  · simp
  · exact l_lt_of_mem hx

/-- **The `G_k`-bound of the level-free hull.**  If `β ≼ Ω_{k+1}`, every member of `C(α, β)`
has its `G_k`-arguments below `α`: the only clause that creates a `G_k`-argument is `ofTheta`
at a level `j > k`, and it demands the argument `≺ α`. -/
theorem CsetS.G_lt (k : ℕ) {a b g : ThetaWTerm} (h : CsetS a b g) (hg : NF g)
    (hb : b ≤ Omega k) : ∀ y ∈ G k g, y < a := by
  revert hg
  induction h with
  | ofOmega j => intro _ y hy; simp at hy
  | ofLt hlt =>
    intro hg y hy
    rw [G_eq_nil_of_lt_Omega hg (lt_of_lt_of_le' hlt hb)] at hy
    simp at hy
  | @ofTheta j g hc hlt hdom ih =>
    intro hg y hy
    by_cases hj : k < j
    · rw [G_theta_of_lt hj] at hy
      rcases List.mem_cons.mp hy with rfl | hy
      · exact hlt
      · exact ih hg.theta_arg y hy
    · rw [G_theta_of_le (Nat.le_of_not_lt hj)] at hy
      simp at hy
  | ofSum _ ih =>
    intro hg y hy
    obtain ⟨x, hx, hyx⟩ := mem_G_sum.mp hy
    exact ih x hx (hg.of_mem hx) y hyx

/-- Proposition 3.9, first half, level `k`: `C(α, ϑ_k α) ∩ Ω_{k+1} ≺* ϑ_k α`. -/
theorem lt_theta_of_CsetS_theta {k : ℕ} {a : ThetaWTerm} : ∀ {d : ThetaWTerm}, NF d →
    CsetS a (theta k a) d → d < Omega k → d < theta k a
  | Omega j, _, _, hΩ => (Omega_lt_theta_iff j k a).mpr ((Omega_lt_Omega_iff j k).mp hΩ)
  | theta j d', hn, hc, hΩ => by
      have hjk : j ≤ k := (theta_lt_Omega_iff j k d').mp hΩ
      rcases Nat.lt_or_eq_of_le hjk with hj | hj
      · exact theta_lt_theta_of_lt_level d' a hj
      · subst hj
        cases hc with
        | ofLt h => exact h
        | ofTheta h1 h2 h3 =>
          refine theta_lt_theta_of_lt h2 fun g hg => ?_
          exact lt_theta_of_CsetS_theta ((nf_theta_iff j d').mp hn |>.of_mem_E hg)
            (h1.E_sub j ((nf_theta_iff j d').mp hn) g hg) (lt_Omega_of_mem_E hg)
  | sum [], _, _, _ => nil_lt_theta k a
  | sum (x :: xs), hn, hc, hΩ => by
      cases hc with
      | ofLt h => exact h
      | ofSum h =>
        rw [cons_lt_theta_iff]
        exact lt_theta_of_CsetS_theta (hn.of_mem List.mem_cons_self) (h x List.mem_cons_self)
          ((cons_lt_Omega_iff k x xs).mp hΩ)
termination_by d => l d
decreasing_by
  · have := l_le_of_mem_E hg; simp; omega
  · simp; omega

/-- Proposition 3.9, second half, level `k`: if `C(α, γ) ∩ Ω_{k+1} ≺* γ` and
`α ∈ C(α, γ)`, then every normal domain `δ ≺ ϑ_k α` lies in `C(α, γ)`.  The lower collapses
enter by `ofLt` (they lie below `Ω_k`, itself a hull member below `Ω_{k+1}`, hence below `γ`). -/
theorem CsetS_of_lt_theta {k : ℕ} {a c : ThetaWTerm} (ha : NF a) (hda : Dom a)
    (hc : ∀ d, NF d → Dom d → CsetS a c d → d < Omega k → d < c) (hac : CsetS a c a) :
    ∀ {d : ThetaWTerm}, NF d → Dom d → d < theta k a → CsetS a c d
  | Omega j, _, _, _ => .ofOmega j
  | theta j d', hn, hd, h => by
      have hjk : j ≤ k := by
        by_contra hjk
        exact absurd h (not_theta_lt_theta_of_lt_level d' a (Nat.lt_of_not_le hjk))
      rcases Nat.lt_or_eq_of_le hjk with hj | hj
      · have hΩc : Omega (k - 1) < c :=
          hc (Omega (k - 1)) (nf_Omega _) (dom_Omega _) (.ofOmega _)
            ((Omega_lt_Omega_iff (k - 1) k).mpr (by omega))
        exact .ofLt (lt_trans' ((theta_lt_Omega_iff j (k - 1) d').mpr (by omega)) hΩc)
      · subst hj
        rcases (theta_lt_theta_iff j d' a).mp h with ⟨h1, h2⟩ | ⟨g, hg, hle⟩
        · have hdd' : Dom d' := hd.theta_arg
          refine .ofTheta (CsetS.of_E_G j hdd' (fun g hg => ?_)
            (fun y hy => lt_trans' (hd.G_lt hy) h1)) h1 hd
          exact CsetS_of_lt_theta ha hda hc hac ((nf_theta_iff j d').mp hn |>.of_mem_E hg)
            (hdd'.of_mem_E hg) (h2 g hg)
        · have hgd : Dom g := hda.of_mem_E hg
          have hgn : NF g := ha.of_mem_E hg
          exact .ofLt (lt_of_le_of_lt' hle
            (hc g hgn hgd (hac.E_sub j ha g hg) (lt_Omega_of_mem_E hg)))
  | sum [], _, _, _ => .ofSum (by simp)
  | sum (y :: ys), hn, hd, h => by
      refine .ofSum fun x hx => ?_
      have hle : x ≤ y := hn.desc.le_head x hx
      have hxn : NF x := hn.of_mem hx
      have hxd : Dom x := hd.of_mem hx
      exact CsetS_of_lt_theta ha hda hc hac hxn hxd
        (lt_of_le_of_lt' hle ((cons_lt_theta_iff k y a ys).mp h))
termination_by d => l d
decreasing_by
  · have := l_le_of_mem_E hg; simp; omega
  · exact l_lt_of_mem hx

/-- The level-free hull is contained in every merged per-level hull `CsetT k`. -/
theorem CsetS.to_CsetT (k : ℕ) {a b g : ThetaWTerm} (h : CsetS a b g) : CsetT k a b g := by
  induction h with
  | ofOmega j => exact .ofOmega j
  | ofLt hlt => exact .ofLt hlt
  | @ofTheta j g _ hlt hdom ih =>
    rcases lt_trichotomy j k with hj | rfl | hj
    · exact .ofThetaLow hj g
    · exact .ofThetaOwn ih hlt hdom
    · exact .ofThetaHigh hj ih
  | ofSum _ ih => exact .ofSum ih

end ThetaWTerm

namespace ThetaWNoteD

open ThetaWTerm

/-! ### The hull on notations -/

/-- The level-free hull `C(α, β)` as a set of notations. -/
def CsetS (a b : ThetaWNoteD) : Set ThetaWNoteD := {g | ThetaWTerm.CsetS a.1 b.1 g.1}

theorem mem_CsetS {a b g : ThetaWNoteD} : g ∈ CsetS a b ↔ ThetaWTerm.CsetS a.1 b.1 g.1 := Iff.rfl

theorem Omega_mem_CsetS (j : ℕ) (a b : ThetaWNoteD) : Omega j ∈ CsetS a b :=
  ThetaWTerm.CsetS.ofOmega j

theorem mem_CsetS_of_lt {a b g : ThetaWNoteD} (h : g < b) : g ∈ CsetS a b :=
  ThetaWTerm.CsetS.ofLt h

/-- Closure under `ϑ_j`, every level `j`, on domain arguments `≺ α`. -/
theorem theta_mem_CsetS (j : ℕ) {a b g : ThetaWNoteD} (h : g ∈ CsetS a b) (hg : g < a)
    (hdom : Dom (ThetaWTerm.theta j g.1)) : thetaD j g hdom ∈ CsetS a b :=
  ThetaWTerm.CsetS.ofTheta h hg hdom

theorem CsetS_subset_Cset (k : ℕ) (a b : ThetaWNoteD) : CsetS a b ⊆ Cset k a b :=
  fun _ h => ThetaWTerm.CsetS.to_CsetT k h

/-- `α ∈ C(α, ϑ_k α)`. -/
theorem mem_CsetS_theta_self (k : ℕ) (a : ThetaWNoteD) (hdom : Dom (ThetaWTerm.theta k a.1)) :
    a ∈ CsetS a (thetaD k a hdom) :=
  ThetaWTerm.CsetS.of_E_G k a.2.2 (fun _ hg => ThetaWTerm.CsetS.ofLt (lt_theta_of_mem_E hg))
    (fun _ hy => hdom.G_lt hy)

/-- `C(α, ϑ_k α) ∩ Ω_{k+1} ≺* ϑ_k α`. -/
theorem lt_theta_of_mem_CsetS {k : ℕ} {a d : ThetaWNoteD} (hdom : Dom (ThetaWTerm.theta k a.1))
    (hd : d ∈ CsetS a (thetaD k a hdom)) (hΩ : d < Omega k) : d < thetaD k a hdom :=
  ThetaWTerm.lt_theta_of_CsetS_theta d.2.1 hd hΩ

/-- **Proposition 3.9 for the level-free hull, every level `k`:**
`ϑ_k α = min {γ | C(α, γ) ∩ Ω_{k+1} ≺* γ and α ∈ C(α, γ)}`. -/
theorem theta_isLeastS (k : ℕ) (a : ThetaWNoteD) (hdom : Dom (ThetaWTerm.theta k a.1)) :
    IsLeast {c : ThetaWNoteD | (∀ d ∈ CsetS a c, d < Omega k → d < c) ∧ a ∈ CsetS a c}
      (thetaD k a hdom) := by
  refine ⟨⟨fun d hd hΩ => lt_theta_of_mem_CsetS hdom hd hΩ, mem_CsetS_theta_self k a hdom⟩, ?_⟩
  rintro c ⟨hc, hac⟩
  by_contra hlt
  have hlt : c < thetaD k a hdom := lt_of_not_ge hlt
  have hcC : c ∈ CsetS a c :=
    ThetaWTerm.CsetS_of_lt_theta a.2.1 a.2.2
      (fun d hdn hdd hdC hdΩ => hc ⟨d, hdn, hdd⟩ hdC hdΩ) hac c.2.1 c.2.2 hlt
  exact absurd (hc c hcC (lt_trans hlt (thetaD_lt_Omega k a hdom))) (lt_irrefl c)

/-! ### The one operator `H_α` -/

/-- `H_α(X) = ⋂ {C(γ, δ) | α ≺ γ and X ⊆ C(γ, δ)}` — one operator for all levels. -/
def HopS (a : ThetaWNoteD) (X : Set ThetaWNoteD) : Set ThetaWNoteD :=
  {x | ∀ c d : ThetaWNoteD, a < c → X ⊆ CsetS c d → x ∈ CsetS c d}

theorem mem_HopS {a x : ThetaWNoteD} {X : Set ThetaWNoteD} :
    x ∈ HopS a X ↔ ∀ c d : ThetaWNoteD, a < c → X ⊆ CsetS c d → x ∈ CsetS c d := Iff.rfl

theorem HopS_subset_CsetS {a c d : ThetaWNoteD} {X : Set ThetaWNoteD} (hac : a < c)
    (hX : X ⊆ CsetS c d) : HopS a X ⊆ CsetS c d :=
  fun _ hx => hx c d hac hX

/-- Proposition 3.11 (a). -/
theorem HopS_subset_HopS {a b : ThetaWNoteD} (h : a < b) (X : Set ThetaWNoteD) :
    HopS a X ⊆ HopS b X :=
  fun _ hx c d hbc hX => hx c d (lt_trans h hbc) hX

theorem HopS_subset_HopS_of_le {a b : ThetaWNoteD} (h : a ≤ b) (X : Set ThetaWNoteD) :
    HopS a X ⊆ HopS b X := by
  rcases lt_or_eq_of_le h with h | rfl
  · exact HopS_subset_HopS h X
  · exact le_rfl

/-- Proposition 3.11 (b), every level `k`. -/
theorem theta_mem_HopS (k : ℕ) {x b : ThetaWNoteD} {X : Set ThetaWNoteD} (hx : x ∈ HopS b X)
    (hxb : x ≤ b) (hdom : Dom (ThetaWTerm.theta k x.1)) : thetaD k x hdom ∈ HopS b X :=
  fun c d hbc hX => theta_mem_CsetS k (hx c d hbc hX) (lt_of_le_of_lt hxb hbc) hdom

/-- The hypothesis `X ⊆ ⋂ {C(γ, ϑ_k γ) | α ≺ γ}` of the collapsing theorem at level `k`
(only the hypothesis is per level; the operator is not). -/
def HullHypS (k : ℕ) (a : ThetaWNoteD) (X : Set ThetaWNoteD) : Prop :=
  ∀ c : ThetaWNoteD, a < c → ∀ hc : Dom (ThetaWTerm.theta k c.1), X ⊆ CsetS c (thetaD k c hc)

theorem HullHypS.subset_CsetS {k : ℕ} {a c : ThetaWNoteD} {X : Set ThetaWNoteD}
    (h : HullHypS k a X) (hac : a < c) (hc : Dom (ThetaWTerm.theta k c.1)) :
    X ⊆ CsetS c (thetaD k c hc) :=
  h c hac hc

theorem HullHypS.mono {k : ℕ} {a b : ThetaWNoteD} {X : Set ThetaWNoteD} (h : HullHypS k a X)
    (hab : a ≤ b) : HullHypS k b X :=
  fun _c hbc hc => h.subset_CsetS (lt_of_le_of_lt hab hbc) hc

theorem HullHypS.HopS_subset {k : ℕ} {a c : ThetaWNoteD} {X : Set ThetaWNoteD}
    (h : HullHypS k a X) (hac : a < c) (hc : Dom (ThetaWTerm.theta k c.1)) :
    HopS a X ⊆ CsetS c (thetaD k c hc) :=
  HopS_subset_CsetS hac (h.subset_CsetS hac hc)

theorem HullHypS.lt_theta {k : ℕ} {a c d : ThetaWNoteD} {X : Set ThetaWNoteD}
    (h : HullHypS k a X) (hac : a < c) (hc : Dom (ThetaWTerm.theta k c.1)) (hd : d ∈ HopS a X)
    (hΩ : d < Omega k) : d < thetaD k c hc :=
  lt_theta_of_mem_CsetS hc (h.HopS_subset hac hc hd) hΩ

theorem HullHypS.union_singleton {k : ℕ} {a d g : ThetaWNoteD} {X : Set ThetaWNoteD}
    (h : HullHypS k a X) (hd : d ∈ HopS a X) (hΩ : d < Omega k) (hgd : g < d) :
    HullHypS k a (X ∪ {g}) :=
  fun _c hac hc => Set.union_subset (h.subset_CsetS hac hc)
    (Set.singleton_subset_iff.mpr (mem_CsetS_of_lt (lt_trans hgd (h.lt_theta hac hc hd hΩ))))

/-- Proposition 3.11 (c), every level `k`. -/
theorem theta_lt_theta_of_mem_HopS {k : ℕ} {base x y : ThetaWNoteD} {X : Set ThetaWNoteD}
    (hX : HullHypS k base X) (hbx : base ≤ x) (hxy : x < y) (hx : x ∈ HopS base X)
    (hdomx : Dom (ThetaWTerm.theta k x.1)) (hdomy : Dom (ThetaWTerm.theta k y.1)) :
    thetaD k x hdomx < thetaD k y hdomy := by
  have h1 : thetaD k x hdomx ∈ HopS x X :=
    theta_mem_HopS k (HopS_subset_HopS_of_le hbx X hx) le_rfl hdomx
  have hXy : X ⊆ CsetS y (thetaD k y hdomy) := hX y (lt_of_le_of_lt hbx hxy) hdomy
  exact lt_theta_of_mem_CsetS hdomy (h1 y (thetaD k y hdomy) hxy hXy) (thetaD_lt_Omega k x hdomx)

/-! ### Niceness for the atomic support -/

/-- The atoms `Atoms(α)` as a set of notations (the all-level `E`). -/
def Ahull (a : ThetaWNoteD) : Set ThetaWNoteD := {g | g.1 ∈ Atoms a.1}

theorem mem_Ahull_iff_entries {a g : ThetaWNoteD} :
    g ∈ Ahull a ↔ ∃ e ∈ a.entries, g.1 ∈ Atoms e :=
  mem_Atoms_iff_toList

/-- A nice operator for the atomic support: `α ∈ H(X) ⇔ Atoms(α) ⊆ H(X)` (the audit's
`Notn.Nice supp` with `supp = Ahull`). -/
def NiceS (H : Set ThetaWNoteD → Set ThetaWNoteD) : Prop :=
  IsOperator H ∧ ∀ (X : Set ThetaWNoteD) (a : ThetaWNoteD), a ∈ H X ↔ Ahull a ⊆ H X

theorem NiceS.mem_iff {H : Set ThetaWNoteD → Set ThetaWNoteD} (hH : NiceS H)
    {X : Set ThetaWNoteD} {a : ThetaWNoteD} : a ∈ H X ↔ Ahull a ⊆ H X :=
  hH.2 X a

theorem mem_CsetS_iff_Ahull_subset {a b g : ThetaWNoteD} :
    g ∈ CsetS a b ↔ Ahull g ⊆ CsetS a b := by
  rw [mem_CsetS, ThetaWTerm.CsetS.iff_Atoms g.2.1]
  constructor
  · intro h d hd
    exact h d.1 hd
  · intro h d hd
    exact h (a := ⟨d, g.2.1.of_mem_Atoms hd, g.2.2.of_mem_Atoms hd⟩) hd

theorem HopS_isOperator (a : ThetaWNoteD) : IsOperator (HopS a) :=
  ⟨fun _ _ hx _ _ _ hX => hX hx,
    fun _ _ hXY _ hx c d hac hY => hx c d hac fun _ hy => hXY hy c d hac hY⟩

theorem HopS_nice (a : ThetaWNoteD) : NiceS (HopS a) :=
  ⟨HopS_isOperator a, fun _ _ =>
    ⟨fun hx _ hg c d hac hX => mem_CsetS_iff_Ahull_subset.mp (hx c d hac hX) hg,
      fun h c d hac hX => mem_CsetS_iff_Ahull_subset.mpr fun _ hg => h hg c d hac hX⟩⟩

theorem HopS_mono {a : ThetaWNoteD} {X Y : Set ThetaWNoteD} (h : X ⊆ Y) :
    HopS a X ⊆ HopS a Y :=
  (HopS_isOperator a).mono h

theorem NiceS.adjoin {H : Set ThetaWNoteD → Set ThetaWNoteD} (hH : NiceS H)
    (Z : Set ThetaWNoteD) : NiceS (adjoin H Z) :=
  ⟨hH.1.adjoin Z, fun X a => hH.2 (Z ∪ X) a⟩

@[simp] theorem Ahull_Omega (j : ℕ) : Ahull (Omega j) = ∅ := by
  ext g; change g.1 ∈ Atoms (ThetaWTerm.Omega j) ↔ False; simp

@[simp] theorem Ahull_zero : Ahull zero = ∅ := by
  ext g; change g.1 ∈ Atoms (ThetaWTerm.sum []) ↔ False; simp

theorem Ahull_add_subset (a b : ThetaWNoteD) : Ahull (a + b) ⊆ Ahull a ∪ Ahull b := by
  intro g hg
  obtain ⟨e, he, hge⟩ := mem_Ahull_iff_entries.mp hg
  rw [entries_add] at he
  rcases mem_addL he with he | he
  · exact Or.inl (mem_Ahull_iff_entries.mpr ⟨e, he, hge⟩)
  · exact Or.inr (mem_Ahull_iff_entries.mpr ⟨e, he, hge⟩)

theorem Ahull_nadd_subset (a b : ThetaWNoteD) : Ahull (nadd a b) ⊆ Ahull a ∪ Ahull b := by
  intro g hg
  obtain ⟨e, he, hge⟩ := mem_Ahull_iff_entries.mp hg
  rw [entries_nadd] at he
  rcases mem_mergeL.mp he with he | he
  · exact Or.inl (mem_Ahull_iff_entries.mpr ⟨e, he, hge⟩)
  · exact Or.inr (mem_Ahull_iff_entries.mpr ⟨e, he, hge⟩)

theorem Ahull_omegaPow (a : ThetaWNoteD) : Ahull (omegaPow a) = Ahull a := by
  ext g
  rw [mem_Ahull_iff_entries, entries_omegaPow]
  simp [Ahull]

theorem Ahull_omegaMul_subset (a : ThetaWNoteD) : Ahull (omegaMul a) ⊆ Ahull a := by
  intro g hg
  obtain ⟨e, he, hge⟩ := mem_Ahull_iff_entries.mp hg
  rw [entries_omegaMul] at he
  obtain ⟨d, hd, rfl⟩ := List.mem_map.mp he
  exact mem_Ahull_iff_entries.mpr ⟨d, hd, mem_Atoms_of_mem_Atoms_onePlus hge⟩

@[simp] theorem Ahull_one : Ahull one = ∅ := by
  rw [one, Ahull_omegaPow, Ahull_zero]

@[simp] theorem Ahull_ofNat (n : ℕ) : Ahull (ofNat n) = ∅ := by
  ext g
  simp only [mem_Ahull_iff_entries, entries_ofNat, Set.mem_empty_iff_false, iff_false]
  rintro ⟨e, he, hg⟩
  rw [List.eq_of_mem_replicate he] at hg
  simp at hg

theorem Ahull_succ_subset (a : ThetaWNoteD) : Ahull (succ a) ⊆ Ahull a := by
  intro g hg
  rcases Ahull_nadd_subset a one hg with h | h
  · exact h
  · simp at h

section NiceS

variable {H : Set ThetaWNoteD → Set ThetaWNoteD} (hH : NiceS H) {X : Set ThetaWNoteD}
include hH

theorem NiceS.Omega_mem (j : ℕ) : Omega j ∈ H X := hH.mem_iff.mpr (by simp)

theorem NiceS.zero_mem : zero ∈ H X := hH.mem_iff.mpr (by simp)

theorem NiceS.one_mem : one ∈ H X := hH.mem_iff.mpr (by simp)

theorem NiceS.ofNat_mem (n : ℕ) : ofNat n ∈ H X := hH.mem_iff.mpr (by simp)

theorem NiceS.add_mem {a b : ThetaWNoteD} (ha : a ∈ H X) (hb : b ∈ H X) : a + b ∈ H X :=
  hH.mem_iff.mpr ((Ahull_add_subset a b).trans
    (Set.union_subset (hH.mem_iff.mp ha) (hH.mem_iff.mp hb)))

theorem NiceS.nadd_mem {a b : ThetaWNoteD} (ha : a ∈ H X) (hb : b ∈ H X) : nadd a b ∈ H X :=
  hH.mem_iff.mpr ((Ahull_nadd_subset a b).trans
    (Set.union_subset (hH.mem_iff.mp ha) (hH.mem_iff.mp hb)))

theorem NiceS.omegaMul_mem {a : ThetaWNoteD} (ha : a ∈ H X) : omegaMul a ∈ H X :=
  hH.mem_iff.mpr ((Ahull_omegaMul_subset a).trans (hH.mem_iff.mp ha))

theorem NiceS.omegaPow_mem {a : ThetaWNoteD} (ha : a ∈ H X) : omegaPow a ∈ H X :=
  hH.mem_iff.mpr ((Ahull_omegaPow a).symm ▸ hH.mem_iff.mp ha)

theorem NiceS.succ_mem {a : ThetaWNoteD} (ha : a ∈ H X) : succ a ∈ H X :=
  hH.mem_iff.mpr ((Ahull_succ_subset a).trans (hH.mem_iff.mp ha))

end NiceS

end ThetaWNoteD

end OrdinalAnalysis
